baseurl = "/"
title = "Ryan Schuller"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 8
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Ryan Schuller"
    info = "Software Engineer & Designer"
    description = "Software Engineer & Designer based in Edinburgh."
    keywords = "blog,software,developer,engineer,personal,graphic,design,web"
    avatarurl = "ryan.jpeg"

    hidecredits = true
    hidecopyright = true

    rtl = false
    math = true

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/ryanT5/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/ryan-schuller/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/_ryanschuller"
#[[params.social]]
#    name = "LinkedIn"
#    icon = "fab fa-dribbble"
#    weight = 3
#    url = "https://www.linkedin.com/in/ryan-schuller/"
#[[params.social]]
#    name = "LinkedIn"
#    icon = "fab fa-behance"
#    weight = 4
#    url = "https://www.linkedin.com/in/ryan-schuller/"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url  = "/about/"
[[menu.main]]
    name = "Projects"
    weight = 2
    url = "/projects/"
#[[menu.main]]
#    name = "Practice"
#    weight = 3
#    url = "/practice/"
#[[menu.main]]
#    name = "Blog"
#    weight = 3
#    url = "/posts/"
#[[menu.main]]
#    name = "Contact"
#    weight = 4
#    url = "/contact/"